scraping:
  base_url: "https://understat.com/league"
  leagues:
    - EPL
    - La_liga
    - Bundesliga
    - Serie_A
    - Ligue_1
  seasons:
    start: 2014
    end: 2024

cleansing:
  leagues:
    - EPL
    - La_liga
    - Bundesliga
    - Serie_A
    - Ligue_1
  start_year: 2014
  end_year: 2024
